<section_marker> := "#"
<subsection_marker> := "##"
<subsubsection_marker> := "###"
<list_marker> := "-"
<quote_marker> := ">"
<code_marker> := "```"
<bold_marker> := "*"
<italic_marker> := "/"
<underline_marker> := "_"
<strikethrough_marker> := "~"
<escape_marker> := "\"
<marker> := <section_marker> | <subsection_marker> | <subsubsection_marker> | <list_marker> | <quote_marker> | <code_marker> | <escape_marker>
<style_marker> := <bold_marker> | <italic_marker> | <underline_marker> | <strikethrough_marker>
<valid_char> := <any_char> - <marker> - <style_marker>
<text> := <valid_char> | <text> <valid_char>
<image> := "${" <text> "}"
<special> := <marker> <text>
<paragraph> := <text> | <special> <text> | <style_marker> <text> <style_marker> | <style_marker> <special> <text> <style_marker>
<line> := <paragraph> | <line> <paragraph>
<document> := <line> | <document> <line>